use BD_B65580

CREATE TABLE CATEGORIAS (
	categoria NVARCHAR(25) PRIMARY KEY
);

CREATE TABLE UNIDADES (
	unidad NVARCHAR(25) PRIMARY KEY,
	simbolo NVARCHAR(3)
);

CREATE TABLE PRODUCTO (
	id INT IDENTITY PRIMARY KEY,
	nombre  NVARCHAR(125),
	categoria NVARCHAR(25) FOREIGN KEY REFERENCES CATEGORIAS(categoria),
	unidad NVARCHAR(25) FOREIGN KEY REFERENCES UNIDADES(unidad),
	precio FLOAT, 
	imagen VARBINARY(MAX), 
	tipo VARCHAR(25)
);