use BD_B65580

CREATE TABLE CATEGORIAS (
	categoria NVARCHAR(25) PRIMARY KEY
);

CREATE TABLE UNIDADES (
	unidad NVARCHAR(25) PRIMARY KEY,
	simbolo NVARCHAR(3)
);

CREATE TABLE PRODUCTO (
	id INT IDENTITY PRIMARY KEY,
	nombre  NVARCHAR(125),
	categoria NVARCHAR(25) FOREIGN KEY REFERENCES CATEGORIAS(categoria),
	unidad NVARCHAR(25) FOREIGN KEY REFERENCES UNIDADES(unidad),
	precio FLOAT, 
	imagen VARBINARY(MAX), 
	tipo VARCHAR(25)
);

CREATE TABLE PAQUETE(
	id INT IDENTITY PRIMARY KEY,
	nombre NVARCHAR(250),
	precio MONEY,
);

CREATE TABLE PAQUETE_RELACION(
	paqueteID INT FOREIGN KEY REFERENCES PAQUETE(id),
	productoID INT FOREIGN KEY REFERENCES PRODUCTO(id),
	cantidad INT

	PRIMARY KEY(paqueteID, productoID)
);

CREATE TABLE PEDIDO_PAQUETE(
	PEDIDOID INT FOREIGN KEY REFERENCES PEDIDO(ID),
	PAQUETEID INT FOREIGN KEY REFERENCES PAQUETE(ID),
	CANTIDAD INT
);

CREATE TABLE PEDIDO_PRODUCTO(
PEDIDOID INT FOREIGN KEY REFERENCES PEDIDO(ID),
	PRODUCTOID INT FOREIGN KEY REFERENCES PRODUCTO(ID),
	CANTIDAD INT
);