// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PruebaCarritoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void pruebaCarrito() {
    driver.Navigate().GoToUrl("https://localhost:44398/");
    driver.Manage().Window.Size = new System.Drawing.Size(1064, 816);
    driver.FindElement(By.LinkText("Nuestros productos")).Click();
    driver.FindElement(By.CssSelector(".TarjetaProducto:nth-child(1) button:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".TarjetaProducto:nth-child(1) > .botonAgregar")).Click();
    driver.FindElement(By.Id("mensaje-exito")).Click();
    driver.FindElement(By.CssSelector(".TarjetaProducto:nth-child(2) button:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".TarjetaProducto:nth-child(2) > .botonAgregar")).Click();
    driver.FindElement(By.Id("mensaje-exito")).Click();
    driver.FindElement(By.CssSelector(".TarjetaProducto:nth-child(3) button:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".TarjetaProducto:nth-child(3) > .botonAgregar")).Click();
    driver.FindElement(By.Id("mensaje-exito")).Click();
    driver.FindElement(By.LinkText("Carrito")).Click();
    {
      var element = driver.FindElement(By.LinkText("Carrito"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector("tr:nth-child(3) .btn")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(3) .btn")).Click();
    driver.FindElement(By.CssSelector(".alert-danger")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".carrito-container > .text-center")).Text, Is.EqualTo("Tu carrito está vacio"));
  }
}
