// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PruebavalornuloTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void pruebavalornulo() {
    // Test name: Prueba valor nulo
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://localhost:44398/");
    // 2 | setWindowSize | 1064x816 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1064, 816);
    // 3 | click | linkText=Nuestros productos | 
    driver.FindElement(By.LinkText("Nuestros productos")).Click();
    // 4 | click | id=number2 | 
    driver.FindElement(By.Id("number2")).Click();
    // 5 | type | id=number2 | -25
    driver.FindElement(By.Id("number2")).SendKeys("-25");
    // 6 | click | css=.TarjetaProducto:nth-child(2) > .botonAgregar | 
    driver.FindElement(By.CssSelector(".TarjetaProducto:nth-child(2) > .botonAgregar")).Click();
    // 7 | assertText | id=mensaje | Hay un error en las cantidades ingresadas
    Assert.That(driver.FindElement(By.Id("mensaje")).Text, Is.EqualTo("Hay un error en las cantidades ingresadas"));
  }
}
